// SPDX-License-Identifier: LGPL-2.1-or-later
//! Compact native-style status codes; formatting stays outside hot decode calls.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Fault {
    UuOnlyIp,
    UuExtendedVcl,
    Code420CropAlignment,
    AuHasNoPicture,
    AvccParameterEntry,
    CabacDcRange,
    CabacQpDelta,
    CabacAlignment,
    CabacAlreadyTerminated,
    CabacInitialOffset,
    CabacInitialization,
    CabacLevelPrefix,
    CabacResidualGeometry,
    CavlcCoefficientCount,
    CavlcLevelPrefix,
    CavlcPrefix,
    CavlcResidualGeometry,
    CavlcRunBefore,
    CavlcTotalZeros,
    CbpCode,
    DcBlockShape,
    DcCoefficientRange,
    DpbCapacity,
    DpbHasNoSlidingReference,
    DspBlockGeometry,
    ExpGolombOverflow,
    MmcoDifference,
    MmcoMissingShortReference,
    Mmco5OrderOverflow,
    MvdPrefix,
    NalHeader,
    PSubpartitionType,
    PcmAlignment,
    PcmMacroblockSequence,
    PcmSampleCount,
    Pps,
    PpsId,
    Rbsp,
    Sps,
    SpsId,
    ActiveReferenceCount,
    BitWidth,
    BlockOutsidePicture,
    BypassResidualGeometry,
    ChromaIntraMode,
    ChromaMode,
    ChromaPartition,
    CodedSizeOrCrop,
    DeblockFootprint,
    DeblockParameters,
    ExtradataIsNotAParameterSet,
    HorizontalCrop,
    IncompatibleReferenceLayout,
    IncompleteMacroblockPartitions,
    IncompleteOrFailedPicture,
    IntraNxnMode,
    IntraBorderGeometry,
    IntraEdgeGeometry,
    Intra16Mode,
    LongReferenceIndex,
    LumaPartition,
    MacroblockQpDelta,
    MacroblockParameters,
    MacroblockSequence,
    MacroblockType,
    MissingAnnexBParameterPrefix,
    MissingActiveReference,
    MissingFirstMacroblock,
    MixedPictureIdentities,
    MotionVectorRange,
    ParameterNalTooLarge,
    ParameterChangeWithinPicture,
    PartitionCount,
    PartitionGeometry,
    PartitionOverlap,
    PartitionWithoutReference,
    PartitionedExtendedAvc,
    PictureOrder,
    PlaneGeometry,
    PredictionWeight,
    ReferenceIdentityOverflow,
    ReferenceIndex,
    ReferenceListHole,
    ReferenceReorderingDelta,
    SignedExpGolombOverflow,
    SliceHeader,
    SliceQuantizer,
    SliceTrailingBits,
    StreamingFrameFormat,
    TooManyMacroblocks,
    TransformBlockShape,
    UnavailableIntraNeighbour,
    UnavailableReorderedReference,
    UnterminatedSlice,
    VerticalCrop,
    ZeroScalingWeight,
}
impl Fault {
    pub fn message(self) -> &'static str {
        match self {
            Self::UuOnlyIp => "UU H264 contract accepts only I/P slices",
            Self::UuExtendedVcl => "UU H264 contract excludes partitioned/extended VCL",
            Self::Code420CropAlignment => "420 crop alignment",
            Self::AuHasNoPicture => "AU has no picture",
            Self::AvccParameterEntry => "AVCC parameter entry",
            Self::CabacDcRange => "CABAC DC range",
            Self::CabacQpDelta => "CABAC QP delta",
            Self::CabacAlignment => "CABAC alignment",
            Self::CabacAlreadyTerminated => "CABAC already terminated",
            Self::CabacInitialOffset => "CABAC initial offset",
            Self::CabacInitialization => "CABAC initialization",
            Self::CabacLevelPrefix => "CABAC level prefix",
            Self::CabacResidualGeometry => "CABAC residual geometry",
            Self::CavlcCoefficientCount => "CAVLC coefficient count",
            Self::CavlcLevelPrefix => "CAVLC level prefix",
            Self::CavlcPrefix => "CAVLC prefix",
            Self::CavlcResidualGeometry => "CAVLC residual geometry",
            Self::CavlcRunBefore => "CAVLC run before",
            Self::CavlcTotalZeros => "CAVLC total zeros",
            Self::CbpCode => "CBP code",
            Self::DcBlockShape => "DC block shape",
            Self::DcCoefficientRange => "DC coefficient range",
            Self::DpbCapacity => "DPB capacity",
            Self::DpbHasNoSlidingReference => "DPB has no sliding reference",
            Self::DspBlockGeometry => "DSP block geometry",
            Self::ExpGolombOverflow => "Exp-Golomb overflow",
            Self::MmcoDifference => "MMCO difference",
            Self::MmcoMissingShortReference => "MMCO missing short reference",
            Self::Mmco5OrderOverflow => "MMCO5 order overflow",
            Self::MvdPrefix => "MVD prefix",
            Self::NalHeader => "NAL header",
            Self::PSubpartitionType => "P subpartition type",
            Self::PcmAlignment => "PCM alignment",
            Self::PcmMacroblockSequence => "PCM macroblock sequence",
            Self::PcmSampleCount => "PCM sample count",
            Self::Pps => "PPS",
            Self::PpsId => "PPS id",
            Self::Rbsp => "RBSP",
            Self::Sps => "SPS",
            Self::SpsId => "SPS id",
            Self::ActiveReferenceCount => "active reference count",
            Self::BitWidth => "bit width",
            Self::BlockOutsidePicture => "block outside picture",
            Self::BypassResidualGeometry => "bypass residual geometry",
            Self::ChromaIntraMode => "chroma intra mode",
            Self::ChromaMode => "chroma mode",
            Self::ChromaPartition => "chroma partition",
            Self::CodedSizeOrCrop => "coded size or crop",
            Self::DeblockFootprint => "deblock footprint",
            Self::DeblockParameters => "deblock parameters",
            Self::ExtradataIsNotAParameterSet => "extradata is not a parameter set",
            Self::HorizontalCrop => "horizontal crop",
            Self::IncompatibleReferenceLayout => "incompatible reference layout",
            Self::IncompleteMacroblockPartitions => "incomplete macroblock partitions",
            Self::IncompleteOrFailedPicture => "incomplete or failed picture",
            Self::IntraNxnMode => "intra NxN mode",
            Self::IntraBorderGeometry => "intra border geometry",
            Self::IntraEdgeGeometry => "intra edge geometry",
            Self::Intra16Mode => "intra16 mode",
            Self::LongReferenceIndex => "long reference index",
            Self::LumaPartition => "luma partition",
            Self::MacroblockQpDelta => "macroblock QP delta",
            Self::MacroblockParameters => "macroblock parameters",
            Self::MacroblockSequence => "macroblock sequence",
            Self::MacroblockType => "macroblock type",
            Self::MissingAnnexBParameterPrefix => "missing Annex-B parameter prefix",
            Self::MissingActiveReference => "missing active reference",
            Self::MissingFirstMacroblock => "missing first macroblock",
            Self::MixedPictureIdentities => "mixed picture identities",
            Self::MotionVectorRange => "motion vector range",
            Self::ParameterNalTooLarge => "parameter NAL too large",
            Self::ParameterChangeWithinPicture => "parameter change within picture",
            Self::PartitionCount => "partition count",
            Self::PartitionGeometry => "partition geometry",
            Self::PartitionOverlap => "partition overlap",
            Self::PartitionWithoutReference => "partition without reference",
            Self::PartitionedExtendedAvc => "partitioned/extended AVC",
            Self::PictureOrder => "picture order",
            Self::PlaneGeometry => "plane geometry",
            Self::PredictionWeight => "prediction weight",
            Self::ReferenceIdentityOverflow => "reference identity overflow",
            Self::ReferenceIndex => "reference index",
            Self::ReferenceListHole => "reference list hole",
            Self::ReferenceReorderingDelta => "reference reordering delta",
            Self::SignedExpGolombOverflow => "signed Exp-Golomb overflow",
            Self::SliceHeader => "slice header",
            Self::SliceQuantizer => "slice quantizer",
            Self::SliceTrailingBits => "slice trailing bits",
            Self::StreamingFrameFormat => "streaming frame format",
            Self::TooManyMacroblocks => "too many macroblocks",
            Self::TransformBlockShape => "transform block shape",
            Self::UnavailableIntraNeighbour => "unavailable intra neighbour",
            Self::UnavailableReorderedReference => "unavailable reordered reference",
            Self::UnterminatedSlice => "unterminated slice",
            Self::VerticalCrop => "vertical crop",
            Self::ZeroScalingWeight => "zero scaling weight",
        }
    }
}
